apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service 
  labels:
    app: weather-service 
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: weather-service 
  template:
    metadata:
      labels:
        app: weather-service 
    spec:
      containers:
      - name: auth-service
        image: ckumar483/weather-service
        ports:
        - containerPort: 8001
