apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: poc-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: application.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ambassador
          servicePort: 80
